apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: redis-client
build:
  artifacts:
  - image: darrenlin915/redisdotnetsample
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - app.yaml
