apiVersion: apps/v1
kind: Deployment
metadata:
  name:  ubuntu
  namespace: default
  labels:
    app:  ubuntu
spec:
  selector:
    matchLabels:
      app: ubuntu
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  ubuntu
    spec:
      containers:
      - name:  ubuntu
        image: redis
        command:
          - "sleep"
          - "604800"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: "2"
            memory: 2Gi