apiVersion: apps/v1
kind: Deployment

metadata:
  name: redis-test
  namespace: dotnet-sample
spec:
  replicas: 10
  selector:
    matchLabels:
      app: redis-test
  template:
    metadata:
      labels:
        app: redis-test
    spec:
      containers:
      - name: redis-test
        env:
        - name: REDIS_ENDPOINT
          value: cdm9m8ue6l9kg5n.lm5w0w.clustercfg.usw2.cache.amazonaws.com
        - name: STRESS_MODE
          value: "false"
        image: darrenlin915/redisdotnetsample
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        # ports:
        # - containerPort: <Port>

