apiVersion: apps/v1
kind: Deployment

metadata:
  name: redis-test
  namespace: dotnet-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-test
  template:
    metadata:
      labels:
        app: redis-test
    spec:
      containers:
      - name: redis-test
        env:
        - name: REDIS_ENDPOINT
          value: cdm9m8ue6l9kg5n.lm5w0w.clustercfg.usw2.cache.amazonaws.com
        - name: STRESS_MODE
          value: "OFF"
        - name: DBFLUSH
          value: "FALSE"
        image: darrenlin915/redisdotnetsample
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            cpu: "2"
            memory: "256Mi"
        # ports:
        # - containerPort: <Port>

