apiVersion: skaffold/v2beta23
kind: Config
metadata:
  name: stackexchange-redis-test
build:
  artifacts:
  - image: darrenlin915/redisdotnetsample
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - deploy/app.yaml
